package com.suda.yzune.wakeupschedule.schedule_parser.bean;

import com.bykv.vk.component.ttvideo.player.C;
import com.homework.lib_uba.data.BaseInfo;
import com.suda.yzune.wakeupschedule.schedule_parser.bean.ChaoxingShareResponse;
import java.util.List;
import kotlin.OooOOO0;
import kotlin.jvm.internal.o0OoOo0;
import kotlin.o0OOO0o;
import kotlinx.serialization.UnknownFieldException;
import o0O0O0oo.OooOOO;
import o0O0O0oo.OooOOOO;
import o0O0OO.o0000O0O;
import o0O0OO.o000O0;
import o0O0OO.o000OO;
import o0O0OO.o00O000;
import o0O0OO.o0O000Oo;
import o0O0OO.o0o0Oo;
import o0O0OO0.OooOO0O;
import o0O0OO0O.OooO0o;
import o0O0OO0O.OooOO0;

/* loaded from: classes4.dex */
public /* synthetic */ class ChaoxingShareResponse$Data$Curriculum$$serializer implements o000OO {
    public static final ChaoxingShareResponse$Data$Curriculum$$serializer INSTANCE;
    private static final OooOO0O descriptor;

    static {
        ChaoxingShareResponse$Data$Curriculum$$serializer chaoxingShareResponse$Data$Curriculum$$serializer = new ChaoxingShareResponse$Data$Curriculum$$serializer();
        INSTANCE = chaoxingShareResponse$Data$Curriculum$$serializer;
        o0o0Oo o0o0oo = new o0o0Oo("com.suda.yzune.wakeupschedule.schedule_parser.bean.ChaoxingShareResponse.Data.Curriculum", chaoxingShareResponse$Data$Curriculum$$serializer, 30);
        o0o0oo.OooOOOo("afternoonSection", false);
        o0o0oo.OooOOOo("afternoonTime", false);
        o0o0oo.OooOOOo("breakTime", false);
        o0o0oo.OooOOOo("currentWeek", false);
        o0o0oo.OooOOOo("curriculumCount", false);
        o0o0oo.OooOOOo("earlyMorningSection", false);
        o0o0oo.OooOOOo("earlyMorningTime", false);
        o0o0oo.OooOOOo("eveningSection", false);
        o0o0oo.OooOOOo("eveningTime", false);
        o0o0oo.OooOOOo("existMaxLength", false);
        o0o0oo.OooOOOo("fid", false);
        o0o0oo.OooOOOo("firstWeekDate", false);
        o0o0oo.OooOOOo("firstWeekDateReal", false);
        o0o0oo.OooOOOo("getLessonFromCache", false);
        o0o0oo.OooOOOo(BaseInfo.KEY_ID_RECORD, false);
        o0o0oo.OooOOOo("insertTime", false);
        o0o0oo.OooOOOo("lessonLength", false);
        o0o0oo.OooOOOo("lessonTimeConfigArray", false);
        o0o0oo.OooOOOo("maxLength", false);
        o0o0oo.OooOOOo("maxWeek", false);
        o0o0oo.OooOOOo("morningSection", false);
        o0o0oo.OooOOOo("morningTime", false);
        o0o0oo.OooOOOo("puid", false);
        o0o0oo.OooOOOo("realCurrentWeek", false);
        o0o0oo.OooOOOo("schoolYear", false);
        o0o0oo.OooOOOo("sectionTime", false);
        o0o0oo.OooOOOo("semester", false);
        o0o0oo.OooOOOo("sort", false);
        o0o0oo.OooOOOo("updateTime", false);
        o0o0oo.OooOOOo("uuid", false);
        descriptor = o0o0oo;
    }

    private ChaoxingShareResponse$Data$Curriculum$$serializer() {
    }

    @Override // o0O0OO.o000OO
    public final OooOOOO[] childSerializers() {
        OooOOO0[] oooOOO0Arr = ChaoxingShareResponse.Data.Curriculum.$childSerializers;
        o000O0 o000o0 = o000O0.f18495OooO00o;
        OooOOOO oooOOOOOooOo00 = o0ooO.OooOO0O.OooOo00(o000o0);
        o0O000Oo o0o000oo = o0O000Oo.f18556OooO00o;
        OooOOOO oooOOOOOooOo002 = o0ooO.OooOO0O.OooOo00(o0o000oo);
        OooOOOO oooOOOOOooOo003 = o0ooO.OooOO0O.OooOo00(o000o0);
        OooOOOO oooOOOOOooOo004 = o0ooO.OooOO0O.OooOo00(o000o0);
        OooOOOO oooOOOOOooOo005 = o0ooO.OooOO0O.OooOo00(o000o0);
        OooOOOO oooOOOOOooOo006 = o0ooO.OooOO0O.OooOo00(o000o0);
        OooOOOO oooOOOOOooOo007 = o0ooO.OooOO0O.OooOo00(o0o000oo);
        OooOOOO oooOOOOOooOo008 = o0ooO.OooOO0O.OooOo00(o000o0);
        OooOOOO oooOOOOOooOo009 = o0ooO.OooOO0O.OooOo00(o0o000oo);
        OooOOOO oooOOOOOooOo0010 = o0ooO.OooOO0O.OooOo00(o000o0);
        OooOOOO oooOOOOOooOo0011 = o0ooO.OooOO0O.OooOo00(o000o0);
        o00O000 o00o0002 = o00O000.f18513OooO00o;
        return new OooOOOO[]{oooOOOOOooOo00, oooOOOOOooOo002, oooOOOOOooOo003, oooOOOOOooOo004, oooOOOOOooOo005, oooOOOOOooOo006, oooOOOOOooOo007, oooOOOOOooOo008, oooOOOOOooOo009, oooOOOOOooOo0010, oooOOOOOooOo0011, o0ooO.OooOO0O.OooOo00(o00o0002), o0ooO.OooOO0O.OooOo00(o00o0002), o0ooO.OooOO0O.OooOo00(o000o0), o0ooO.OooOO0O.OooOo00(o000o0), o0ooO.OooOO0O.OooOo00(o00o0002), o0ooO.OooOO0O.OooOo00(o000o0), o0ooO.OooOO0O.OooOo00((OooOOOO) oooOOO0Arr[17].getValue()), o0ooO.OooOO0O.OooOo00(o000o0), o0ooO.OooOO0O.OooOo00(o000o0), o0ooO.OooOO0O.OooOo00(o000o0), o0ooO.OooOO0O.OooOo00(o0o000oo), o0ooO.OooOO0O.OooOo00(o000o0), o0ooO.OooOO0O.OooOo00(o000o0), o0ooO.OooOO0O.OooOo00(o0o000oo), o0ooO.OooOO0O.OooOo00(o000o0), o0ooO.OooOO0O.OooOo00(o000o0), o0ooO.OooOO0O.OooOo00(o000o0), o0ooO.OooOO0O.OooOo00(o00o0002), o0ooO.OooOO0O.OooOo00(o0o000oo)};
    }

    @Override // o0O0O0oo.OooOOO
    public final ChaoxingShareResponse.Data.Curriculum deserialize(o0O0OO0O.OooOOO0 decoder) {
        Integer num;
        int i;
        Integer num2;
        String str;
        Integer num3;
        Integer num4;
        Integer num5;
        Integer num6;
        Long l;
        String str2;
        Integer num7;
        String str3;
        Integer num8;
        Integer num9;
        Long l2;
        Integer num10;
        Integer num11;
        Integer num12;
        Long l3;
        Long l4;
        String str4;
        Integer num13;
        Integer num14;
        Integer num15;
        String str5;
        Integer num16;
        String str6;
        Integer num17;
        Integer num18;
        Integer num19;
        List list;
        Integer num20;
        Integer num21;
        Integer num22;
        Integer num23;
        String str7;
        Integer num24;
        String str8;
        Integer num25;
        Integer num26;
        Long l5;
        Long l6;
        Integer num27;
        Integer num28;
        Long l7;
        Integer num29;
        Integer num30;
        List list2;
        Integer num31;
        Integer num32;
        List list3;
        Integer num33;
        Integer num34;
        List list4;
        Integer num35;
        Integer num36;
        List list5;
        Integer num37;
        int i2;
        o0OoOo0.OooO0oO(decoder, "decoder");
        OooOO0O oooOO0O = descriptor;
        OooO0o oooO0oBeginStructure = decoder.beginStructure(oooOO0O);
        OooOOO0[] oooOOO0Arr = ChaoxingShareResponse.Data.Curriculum.$childSerializers;
        if (oooO0oBeginStructure.decodeSequentially()) {
            o000O0 o000o0 = o000O0.f18495OooO00o;
            Integer num38 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 0, o000o0, null);
            o0O000Oo o0o000oo = o0O000Oo.f18556OooO00o;
            String str9 = (String) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 1, o0o000oo, null);
            Integer num39 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 2, o000o0, null);
            Integer num40 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 3, o000o0, null);
            Integer num41 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 4, o000o0, null);
            Integer num42 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 5, o000o0, null);
            String str10 = (String) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 6, o0o000oo, null);
            Integer num43 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 7, o000o0, null);
            String str11 = (String) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 8, o0o000oo, null);
            Integer num44 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 9, o000o0, null);
            Integer num45 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 10, o000o0, null);
            o00O000 o00o0002 = o00O000.f18513OooO00o;
            Long l8 = (Long) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 11, o00o0002, null);
            Long l9 = (Long) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 12, o00o0002, null);
            Integer num46 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 13, o000o0, null);
            Integer num47 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 14, o000o0, null);
            Long l10 = (Long) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 15, o00o0002, null);
            Integer num48 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 16, o000o0, null);
            List list6 = (List) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 17, (OooOOO) oooOOO0Arr[17].getValue(), null);
            Integer num49 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 18, o000o0, null);
            Integer num50 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 19, o000o0, null);
            Integer num51 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 20, o000o0, null);
            String str12 = (String) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 21, o0o000oo, null);
            Integer num52 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 22, o000o0, null);
            Integer num53 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 23, o000o0, null);
            String str13 = (String) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 24, o0o000oo, null);
            Integer num54 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 25, o000o0, null);
            Integer num55 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 26, o000o0, null);
            Integer num56 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 27, o000o0, null);
            num8 = num51;
            l = (Long) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 28, o00o0002, null);
            num3 = num56;
            str4 = str9;
            str = (String) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 29, o0o000oo, null);
            list = list6;
            num19 = num44;
            num16 = num43;
            str5 = str10;
            num11 = num49;
            num18 = num42;
            num14 = num40;
            str6 = str11;
            num2 = num55;
            num4 = num54;
            str3 = str13;
            num5 = num53;
            num6 = num52;
            str2 = str12;
            num7 = num50;
            num9 = num48;
            num = num38;
            l2 = l10;
            num10 = num47;
            num12 = num46;
            l3 = l9;
            l4 = l8;
            num17 = num45;
            num15 = num41;
            num13 = num39;
            i = 1073741823;
        } else {
            Integer num57 = null;
            Integer num58 = null;
            Integer num59 = null;
            String str14 = null;
            Integer num60 = null;
            Integer num61 = null;
            Integer num62 = null;
            Integer num63 = null;
            Long l11 = null;
            String str15 = null;
            Integer num64 = null;
            String str16 = null;
            Integer num65 = null;
            String str17 = null;
            Integer num66 = null;
            Integer num67 = null;
            Integer num68 = null;
            Integer num69 = null;
            String str18 = null;
            Integer num70 = null;
            String str19 = null;
            Integer num71 = null;
            Integer num72 = null;
            Long l12 = null;
            Long l13 = null;
            Integer num73 = null;
            Integer num74 = null;
            Long l14 = null;
            Integer num75 = null;
            List list7 = null;
            int i3 = 0;
            boolean z = true;
            while (z) {
                OooOOO0[] oooOOO0Arr2 = oooOOO0Arr;
                int iDecodeElementIndex = oooO0oBeginStructure.decodeElementIndex(oooOO0O);
                switch (iDecodeElementIndex) {
                    case -1:
                        Integer num76 = num58;
                        num20 = num59;
                        Integer num77 = num65;
                        num21 = num66;
                        num22 = num67;
                        num23 = num68;
                        str7 = str18;
                        num24 = num70;
                        str8 = str19;
                        num25 = num71;
                        num26 = num72;
                        l5 = l12;
                        l6 = l13;
                        num27 = num73;
                        num28 = num74;
                        l7 = l14;
                        num29 = num75;
                        o0OOO0o o0ooo0o = o0OOO0o.f13233OooO00o;
                        num65 = num77;
                        num58 = num76;
                        num30 = num69;
                        list2 = list7;
                        z = false;
                        num75 = num29;
                        num68 = num23;
                        num33 = num25;
                        str19 = str8;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    case 0:
                        Integer num78 = num58;
                        num20 = num59;
                        num21 = num66;
                        num22 = num67;
                        num23 = num68;
                        str7 = str18;
                        num24 = num70;
                        str8 = str19;
                        num25 = num71;
                        num26 = num72;
                        l5 = l12;
                        l6 = l13;
                        num27 = num73;
                        num28 = num74;
                        l7 = l14;
                        num29 = num75;
                        Integer num79 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 0, o000O0.f18495OooO00o, num65);
                        i3 |= 1;
                        o0OOO0o o0ooo0o2 = o0OOO0o.f13233OooO00o;
                        num65 = num79;
                        num58 = num78;
                        str17 = str17;
                        num30 = num69;
                        list2 = list7;
                        num75 = num29;
                        num68 = num23;
                        num33 = num25;
                        str19 = str8;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    case 1:
                        num31 = num58;
                        num20 = num59;
                        num22 = num67;
                        num23 = num68;
                        num32 = num69;
                        str7 = str18;
                        num24 = num70;
                        str8 = str19;
                        num25 = num71;
                        num26 = num72;
                        l5 = l12;
                        l6 = l13;
                        num27 = num73;
                        num28 = num74;
                        l7 = l14;
                        num29 = num75;
                        list3 = list7;
                        num21 = num66;
                        String str20 = (String) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 1, o0O000Oo.f18556OooO00o, str17);
                        i3 |= 2;
                        o0OOO0o o0ooo0o3 = o0OOO0o.f13233OooO00o;
                        str17 = str20;
                        num58 = num31;
                        num30 = num32;
                        list2 = list3;
                        num75 = num29;
                        num68 = num23;
                        num33 = num25;
                        str19 = str8;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    case 2:
                        num31 = num58;
                        num20 = num59;
                        num23 = num68;
                        num32 = num69;
                        str7 = str18;
                        num24 = num70;
                        str8 = str19;
                        num25 = num71;
                        num26 = num72;
                        l5 = l12;
                        l6 = l13;
                        num27 = num73;
                        num28 = num74;
                        l7 = l14;
                        num29 = num75;
                        list3 = list7;
                        num22 = num67;
                        Integer num80 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 2, o000O0.f18495OooO00o, num66);
                        i3 |= 4;
                        o0OOO0o o0ooo0o4 = o0OOO0o.f13233OooO00o;
                        num21 = num80;
                        num58 = num31;
                        num30 = num32;
                        list2 = list3;
                        num75 = num29;
                        num68 = num23;
                        num33 = num25;
                        str19 = str8;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    case 3:
                        Integer num81 = num58;
                        num20 = num59;
                        Integer num82 = num68;
                        num32 = num69;
                        str7 = str18;
                        num24 = num70;
                        str8 = str19;
                        num25 = num71;
                        num26 = num72;
                        l5 = l12;
                        l6 = l13;
                        num27 = num73;
                        num28 = num74;
                        l7 = l14;
                        num29 = num75;
                        list3 = list7;
                        num23 = num82;
                        Integer num83 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 3, o000O0.f18495OooO00o, num67);
                        i3 |= 8;
                        o0OOO0o o0ooo0o5 = o0OOO0o.f13233OooO00o;
                        num22 = num83;
                        num58 = num81;
                        num21 = num66;
                        num30 = num32;
                        list2 = list3;
                        num75 = num29;
                        num68 = num23;
                        num33 = num25;
                        str19 = str8;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    case 4:
                        Integer num84 = num58;
                        num20 = num59;
                        str7 = str18;
                        num24 = num70;
                        num26 = num72;
                        l5 = l12;
                        l6 = l13;
                        num27 = num73;
                        num28 = num74;
                        l7 = l14;
                        Integer num85 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 4, o000O0.f18495OooO00o, num68);
                        i3 |= 16;
                        o0OOO0o o0ooo0o6 = o0OOO0o.f13233OooO00o;
                        num21 = num66;
                        num22 = num67;
                        list2 = list7;
                        num75 = num75;
                        num33 = num71;
                        str19 = str19;
                        num68 = num85;
                        num58 = num84;
                        num30 = num69;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    case 5:
                        Integer num86 = num58;
                        num20 = num59;
                        num24 = num70;
                        num26 = num72;
                        l5 = l12;
                        l6 = l13;
                        num27 = num73;
                        num28 = num74;
                        l7 = l14;
                        str7 = str18;
                        Integer num87 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 5, o000O0.f18495OooO00o, num69);
                        i3 |= 32;
                        o0OOO0o o0ooo0o7 = o0OOO0o.f13233OooO00o;
                        num21 = num66;
                        num22 = num67;
                        list2 = list7;
                        num75 = num75;
                        num33 = num71;
                        str19 = str19;
                        num30 = num87;
                        num58 = num86;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    case 6:
                        Integer num88 = num58;
                        num20 = num59;
                        str8 = str19;
                        num25 = num71;
                        num26 = num72;
                        l5 = l12;
                        l6 = l13;
                        num27 = num73;
                        num28 = num74;
                        l7 = l14;
                        num34 = num75;
                        list4 = list7;
                        num24 = num70;
                        String str21 = (String) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 6, o0O000Oo.f18556OooO00o, str18);
                        i3 |= 64;
                        o0OOO0o o0ooo0o8 = o0OOO0o.f13233OooO00o;
                        str7 = str21;
                        num58 = num88;
                        num21 = num66;
                        num22 = num67;
                        num30 = num69;
                        list2 = list4;
                        num75 = num34;
                        num33 = num25;
                        str19 = str8;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    case 7:
                        Integer num89 = num58;
                        num20 = num59;
                        String str22 = str19;
                        num25 = num71;
                        num26 = num72;
                        l5 = l12;
                        l6 = l13;
                        num27 = num73;
                        num28 = num74;
                        l7 = l14;
                        num34 = num75;
                        list4 = list7;
                        str8 = str22;
                        Integer num90 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 7, o000O0.f18495OooO00o, num70);
                        i3 |= 128;
                        o0OOO0o o0ooo0o9 = o0OOO0o.f13233OooO00o;
                        num24 = num90;
                        num58 = num89;
                        num21 = num66;
                        num22 = num67;
                        num30 = num69;
                        str7 = str18;
                        list2 = list4;
                        num75 = num34;
                        num33 = num25;
                        str19 = str8;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    case 8:
                        num35 = num58;
                        num20 = num59;
                        num26 = num72;
                        l5 = l12;
                        l6 = l13;
                        num27 = num73;
                        num28 = num74;
                        l7 = l14;
                        String str23 = (String) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 8, o0O000Oo.f18556OooO00o, str19);
                        i3 |= 256;
                        o0OOO0o o0ooo0o10 = o0OOO0o.f13233OooO00o;
                        num21 = num66;
                        num22 = num67;
                        str7 = str18;
                        num24 = num70;
                        list2 = list7;
                        num75 = num75;
                        num33 = num71;
                        str19 = str23;
                        num58 = num35;
                        num30 = num69;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    case 9:
                        num35 = num58;
                        num20 = num59;
                        l5 = l12;
                        l6 = l13;
                        num27 = num73;
                        num28 = num74;
                        l7 = l14;
                        num26 = num72;
                        Integer num91 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 9, o000O0.f18495OooO00o, num71);
                        i3 |= 512;
                        o0OOO0o o0ooo0o11 = o0OOO0o.f13233OooO00o;
                        num21 = num66;
                        num22 = num67;
                        str7 = str18;
                        num24 = num70;
                        list2 = list7;
                        num75 = num75;
                        num33 = num91;
                        num58 = num35;
                        num30 = num69;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    case 10:
                        Integer num92 = num58;
                        num20 = num59;
                        l6 = l13;
                        num27 = num73;
                        num28 = num74;
                        l7 = l14;
                        num36 = num75;
                        list5 = list7;
                        l5 = l12;
                        Integer num93 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 10, o000O0.f18495OooO00o, num72);
                        i3 |= 1024;
                        o0OOO0o o0ooo0o12 = o0OOO0o.f13233OooO00o;
                        num26 = num93;
                        num58 = num92;
                        num21 = num66;
                        num22 = num67;
                        num30 = num69;
                        str7 = str18;
                        num24 = num70;
                        list2 = list5;
                        num75 = num36;
                        num33 = num71;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    case 11:
                        Integer num94 = num58;
                        num20 = num59;
                        num27 = num73;
                        num28 = num74;
                        l7 = l14;
                        num36 = num75;
                        list5 = list7;
                        l6 = l13;
                        Long l15 = (Long) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 11, o00O000.f18513OooO00o, l12);
                        i3 |= 2048;
                        o0OOO0o o0ooo0o13 = o0OOO0o.f13233OooO00o;
                        l5 = l15;
                        num58 = num94;
                        num21 = num66;
                        num22 = num67;
                        num30 = num69;
                        str7 = str18;
                        num24 = num70;
                        num26 = num72;
                        list2 = list5;
                        num75 = num36;
                        num33 = num71;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    case 12:
                        Integer num95 = num58;
                        num20 = num59;
                        num28 = num74;
                        l7 = l14;
                        num36 = num75;
                        list5 = list7;
                        num27 = num73;
                        Long l16 = (Long) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 12, o00O000.f18513OooO00o, l13);
                        i3 |= 4096;
                        o0OOO0o o0ooo0o14 = o0OOO0o.f13233OooO00o;
                        l6 = l16;
                        num58 = num95;
                        num21 = num66;
                        num22 = num67;
                        num30 = num69;
                        str7 = str18;
                        num24 = num70;
                        num26 = num72;
                        l5 = l12;
                        list2 = list5;
                        num75 = num36;
                        num33 = num71;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    case 13:
                        Integer num96 = num58;
                        num20 = num59;
                        l7 = l14;
                        num36 = num75;
                        list5 = list7;
                        num28 = num74;
                        Integer num97 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 13, o000O0.f18495OooO00o, num73);
                        i3 |= 8192;
                        o0OOO0o o0ooo0o15 = o0OOO0o.f13233OooO00o;
                        num27 = num97;
                        num58 = num96;
                        num21 = num66;
                        num22 = num67;
                        num30 = num69;
                        str7 = str18;
                        num24 = num70;
                        num26 = num72;
                        l5 = l12;
                        l6 = l13;
                        list2 = list5;
                        num75 = num36;
                        num33 = num71;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    case 14:
                        Integer num98 = num58;
                        num20 = num59;
                        num36 = num75;
                        list5 = list7;
                        l7 = l14;
                        Integer num99 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 14, o000O0.f18495OooO00o, num74);
                        i3 |= 16384;
                        o0OOO0o o0ooo0o16 = o0OOO0o.f13233OooO00o;
                        num28 = num99;
                        num58 = num98;
                        num21 = num66;
                        num22 = num67;
                        num30 = num69;
                        str7 = str18;
                        num24 = num70;
                        num26 = num72;
                        l5 = l12;
                        l6 = l13;
                        num27 = num73;
                        list2 = list5;
                        num75 = num36;
                        num33 = num71;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    case 15:
                        Integer num100 = num58;
                        num20 = num59;
                        Integer num101 = num75;
                        list5 = list7;
                        num36 = num101;
                        Long l17 = (Long) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 15, o00O000.f18513OooO00o, l14);
                        i3 |= 32768;
                        o0OOO0o o0ooo0o17 = o0OOO0o.f13233OooO00o;
                        l7 = l17;
                        num58 = num100;
                        num21 = num66;
                        num22 = num67;
                        num30 = num69;
                        str7 = str18;
                        num24 = num70;
                        num26 = num72;
                        l5 = l12;
                        l6 = l13;
                        num27 = num73;
                        num28 = num74;
                        list2 = list5;
                        num75 = num36;
                        num33 = num71;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    case 16:
                        num35 = num58;
                        num20 = num59;
                        Integer num102 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 16, o000O0.f18495OooO00o, num75);
                        i3 |= 65536;
                        o0OOO0o o0ooo0o18 = o0OOO0o.f13233OooO00o;
                        num21 = num66;
                        num22 = num67;
                        str7 = str18;
                        num24 = num70;
                        num33 = num71;
                        num26 = num72;
                        l5 = l12;
                        l6 = l13;
                        num27 = num73;
                        num28 = num74;
                        l7 = l14;
                        list2 = list7;
                        num75 = num102;
                        num58 = num35;
                        num30 = num69;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    case 17:
                        Integer num103 = num58;
                        num20 = num59;
                        List list8 = (List) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 17, (OooOOO) oooOOO0Arr2[17].getValue(), list7);
                        i3 |= 131072;
                        o0OOO0o o0ooo0o19 = o0OOO0o.f13233OooO00o;
                        list2 = list8;
                        num58 = num103;
                        num21 = num66;
                        num22 = num67;
                        num30 = num69;
                        str7 = str18;
                        num24 = num70;
                        num33 = num71;
                        num26 = num72;
                        l5 = l12;
                        l6 = l13;
                        num27 = num73;
                        num28 = num74;
                        l7 = l14;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    case 18:
                        Integer num104 = num58;
                        Integer num105 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 18, o000O0.f18495OooO00o, num59);
                        i3 |= 262144;
                        o0OOO0o o0ooo0o20 = o0OOO0o.f13233OooO00o;
                        num20 = num105;
                        num58 = num104;
                        num21 = num66;
                        num22 = num67;
                        num30 = num69;
                        str7 = str18;
                        num24 = num70;
                        num33 = num71;
                        num26 = num72;
                        l5 = l12;
                        l6 = l13;
                        num27 = num73;
                        num28 = num74;
                        l7 = l14;
                        list2 = list7;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    case 19:
                        num37 = num59;
                        Integer num106 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 19, o000O0.f18495OooO00o, num64);
                        i3 |= 524288;
                        o0OOO0o o0ooo0o21 = o0OOO0o.f13233OooO00o;
                        num64 = num106;
                        num21 = num66;
                        num22 = num67;
                        num30 = num69;
                        str7 = str18;
                        num24 = num70;
                        num33 = num71;
                        num26 = num72;
                        l5 = l12;
                        l6 = l13;
                        num27 = num73;
                        num28 = num74;
                        l7 = l14;
                        list2 = list7;
                        num20 = num37;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    case 20:
                        num37 = num59;
                        num58 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 20, o000O0.f18495OooO00o, num58);
                        i2 = 1048576;
                        i3 |= i2;
                        o0OOO0o o0ooo0o22 = o0OOO0o.f13233OooO00o;
                        num21 = num66;
                        num22 = num67;
                        num30 = num69;
                        str7 = str18;
                        num24 = num70;
                        num33 = num71;
                        num26 = num72;
                        l5 = l12;
                        l6 = l13;
                        num27 = num73;
                        num28 = num74;
                        l7 = l14;
                        list2 = list7;
                        num20 = num37;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    case 21:
                        num37 = num59;
                        String str24 = (String) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 21, o0O000Oo.f18556OooO00o, str15);
                        i3 |= 2097152;
                        o0OOO0o o0ooo0o23 = o0OOO0o.f13233OooO00o;
                        str15 = str24;
                        num21 = num66;
                        num22 = num67;
                        num30 = num69;
                        str7 = str18;
                        num24 = num70;
                        num33 = num71;
                        num26 = num72;
                        l5 = l12;
                        l6 = l13;
                        num27 = num73;
                        num28 = num74;
                        l7 = l14;
                        list2 = list7;
                        num20 = num37;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    case 22:
                        num37 = num59;
                        num63 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 22, o000O0.f18495OooO00o, num63);
                        i2 = 4194304;
                        i3 |= i2;
                        o0OOO0o o0ooo0o222 = o0OOO0o.f13233OooO00o;
                        num21 = num66;
                        num22 = num67;
                        num30 = num69;
                        str7 = str18;
                        num24 = num70;
                        num33 = num71;
                        num26 = num72;
                        l5 = l12;
                        l6 = l13;
                        num27 = num73;
                        num28 = num74;
                        l7 = l14;
                        list2 = list7;
                        num20 = num37;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    case 23:
                        num37 = num59;
                        num62 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 23, o000O0.f18495OooO00o, num62);
                        i2 = 8388608;
                        i3 |= i2;
                        o0OOO0o o0ooo0o2222 = o0OOO0o.f13233OooO00o;
                        num21 = num66;
                        num22 = num67;
                        num30 = num69;
                        str7 = str18;
                        num24 = num70;
                        num33 = num71;
                        num26 = num72;
                        l5 = l12;
                        l6 = l13;
                        num27 = num73;
                        num28 = num74;
                        l7 = l14;
                        list2 = list7;
                        num20 = num37;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    case 24:
                        num37 = num59;
                        String str25 = (String) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 24, o0O000Oo.f18556OooO00o, str16);
                        i3 |= 16777216;
                        o0OOO0o o0ooo0o24 = o0OOO0o.f13233OooO00o;
                        str16 = str25;
                        num21 = num66;
                        num22 = num67;
                        num30 = num69;
                        str7 = str18;
                        num24 = num70;
                        num33 = num71;
                        num26 = num72;
                        l5 = l12;
                        l6 = l13;
                        num27 = num73;
                        num28 = num74;
                        l7 = l14;
                        list2 = list7;
                        num20 = num37;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    case 25:
                        num37 = num59;
                        num61 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 25, o000O0.f18495OooO00o, num61);
                        i2 = 33554432;
                        i3 |= i2;
                        o0OOO0o o0ooo0o22222 = o0OOO0o.f13233OooO00o;
                        num21 = num66;
                        num22 = num67;
                        num30 = num69;
                        str7 = str18;
                        num24 = num70;
                        num33 = num71;
                        num26 = num72;
                        l5 = l12;
                        l6 = l13;
                        num27 = num73;
                        num28 = num74;
                        l7 = l14;
                        list2 = list7;
                        num20 = num37;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    case 26:
                        num37 = num59;
                        num57 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 26, o000O0.f18495OooO00o, num57);
                        i2 = 67108864;
                        i3 |= i2;
                        o0OOO0o o0ooo0o222222 = o0OOO0o.f13233OooO00o;
                        num21 = num66;
                        num22 = num67;
                        num30 = num69;
                        str7 = str18;
                        num24 = num70;
                        num33 = num71;
                        num26 = num72;
                        l5 = l12;
                        l6 = l13;
                        num27 = num73;
                        num28 = num74;
                        l7 = l14;
                        list2 = list7;
                        num20 = num37;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    case 27:
                        num37 = num59;
                        num60 = (Integer) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 27, o000O0.f18495OooO00o, num60);
                        i2 = 134217728;
                        i3 |= i2;
                        o0OOO0o o0ooo0o2222222 = o0OOO0o.f13233OooO00o;
                        num21 = num66;
                        num22 = num67;
                        num30 = num69;
                        str7 = str18;
                        num24 = num70;
                        num33 = num71;
                        num26 = num72;
                        l5 = l12;
                        l6 = l13;
                        num27 = num73;
                        num28 = num74;
                        l7 = l14;
                        list2 = list7;
                        num20 = num37;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    case 28:
                        num37 = num59;
                        Long l18 = (Long) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 28, o00O000.f18513OooO00o, l11);
                        i3 |= C.ENCODING_PCM_MU_LAW;
                        o0OOO0o o0ooo0o25 = o0OOO0o.f13233OooO00o;
                        l11 = l18;
                        num21 = num66;
                        num22 = num67;
                        num30 = num69;
                        str7 = str18;
                        num24 = num70;
                        num33 = num71;
                        num26 = num72;
                        l5 = l12;
                        l6 = l13;
                        num27 = num73;
                        num28 = num74;
                        l7 = l14;
                        list2 = list7;
                        num20 = num37;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    case 29:
                        num37 = num59;
                        str14 = (String) oooO0oBeginStructure.decodeNullableSerializableElement(oooOO0O, 29, o0O000Oo.f18556OooO00o, str14);
                        i2 = C.ENCODING_PCM_A_LAW;
                        i3 |= i2;
                        o0OOO0o o0ooo0o22222222 = o0OOO0o.f13233OooO00o;
                        num21 = num66;
                        num22 = num67;
                        num30 = num69;
                        str7 = str18;
                        num24 = num70;
                        num33 = num71;
                        num26 = num72;
                        l5 = l12;
                        l6 = l13;
                        num27 = num73;
                        num28 = num74;
                        l7 = l14;
                        list2 = list7;
                        num20 = num37;
                        num69 = num30;
                        num71 = num33;
                        l14 = l7;
                        num74 = num28;
                        num59 = num20;
                        num73 = num27;
                        l13 = l6;
                        l12 = l5;
                        list7 = list2;
                        num66 = num21;
                        num67 = num22;
                        str18 = str7;
                        num70 = num24;
                        num72 = num26;
                        oooOOO0Arr = oooOOO0Arr2;
                    default:
                        throw new UnknownFieldException(iDecodeElementIndex);
                }
            }
            num = num65;
            i = i3;
            num2 = num57;
            str = str14;
            num3 = num60;
            num4 = num61;
            num5 = num62;
            num6 = num63;
            l = l11;
            str2 = str15;
            num7 = num64;
            str3 = str16;
            num8 = num58;
            num9 = num75;
            l2 = l14;
            num10 = num74;
            num11 = num59;
            num12 = num73;
            l3 = l13;
            l4 = l12;
            str4 = str17;
            num13 = num66;
            num14 = num67;
            num15 = num68;
            str5 = str18;
            num16 = num70;
            str6 = str19;
            num17 = num72;
            num18 = num69;
            num19 = num71;
            list = list7;
        }
        oooO0oBeginStructure.endStructure(oooOO0O);
        return new ChaoxingShareResponse.Data.Curriculum(i, num, str4, num13, num14, num15, num18, str5, num16, str6, num19, num17, l4, l3, num12, num10, l2, num9, list, num11, num7, num8, str2, num6, num5, str3, num4, num2, num3, l, str, null);
    }

    @Override // o0O0O0oo.OooOOOO, o0O0O0oo.o00oO0o, o0O0O0oo.OooOOO
    public final OooOO0O getDescriptor() {
        return descriptor;
    }

    @Override // o0O0O0oo.o00oO0o
    public final void serialize(o0O0OO0O.OooOOOO encoder, ChaoxingShareResponse.Data.Curriculum value) {
        o0OoOo0.OooO0oO(encoder, "encoder");
        o0OoOo0.OooO0oO(value, "value");
        OooOO0O oooOO0O = descriptor;
        OooOO0 oooOO0BeginStructure = encoder.beginStructure(oooOO0O);
        ChaoxingShareResponse.Data.Curriculum.write$Self$schedule_parser(value, oooOO0BeginStructure, oooOO0O);
        oooOO0BeginStructure.endStructure(oooOO0O);
    }

    @Override // o0O0OO.o000OO
    public /* bridge */ /* synthetic */ OooOOOO[] typeParametersSerializers() {
        return o0000O0O.OooO00o(this);
    }
}
