package com.baidu.mobads.container.components.g.a;

/* loaded from: classes2.dex */
public class b {
    public static final int A = 142;
    public static final int B = 143;
    public static final int C = 144;
    public static final int D = 200;
    public static final int E = 201;
    public static final int F = 202;
    public static final int G = 300;
    public static final int H = 301;
    public static final int I = 302;
    public static final int J = 303;
    public static final int K = 304;
    public static final int L = 307;
    public static final int M = 308;
    public static final int N = 309;
    public static final int O = 400;
    public static final int P = 401;
    public static final int Q = 402;
    public static final int R = 404;
    public static final int S = 405;
    public static final int T = 406;
    public static final int U = 407;
    public static final int V = 408;
    public static final int a = 101;
    public static final int b = 102;
    public static final int c = 103;
    public static final int d = 104;
    public static final int e = 105;
    public static final int f = 106;
    public static final int g = 107;
    public static final int h = 108;
    public static final int i = 109;
    public static final int j = 110;
    public static final int k = 111;
    public static final int l = 112;
    public static final int m = 113;
    public static final int n = 114;
    public static final int o = 130;
    public static final int p = 131;
    public static final int q = 132;
    public static final int r = 133;
    public static final int s = 134;
    public static final int t = 135;
    public static final int u = 136;
    public static final int v = 137;
    public static final int w = 138;
    public static final int x = 139;
    public static final int y = 140;
    public static final int z = 141;
}
