package com.kwad.sdk.core.config;

import com.bytedance.pangle.ZeusPluginEventCallback;
import com.kwad.sdk.core.config.item.InstallActivateReminderConfigItem;
import com.kwad.sdk.core.config.item.TipsConfigItem;
import com.kwad.sdk.core.config.item.f;
import com.kwad.sdk.core.config.item.g;
import com.kwad.sdk.core.config.item.h;
import com.kwad.sdk.core.config.item.i;
import com.kwad.sdk.core.config.item.j;
import com.kwad.sdk.core.config.item.k;
import com.kwad.sdk.core.config.item.l;
import com.kwad.sdk.core.config.item.m;
import com.kwad.sdk.core.config.item.n;
import com.kwad.sdk.core.config.item.o;
import com.kwad.sdk.core.config.item.p;
import com.kwad.sdk.core.config.item.q;
import com.kwad.sdk.core.config.item.r;
import com.kwad.sdk.core.config.item.s;
import com.kwad.sdk.core.config.item.t;
import com.kwad.sdk.core.imageloader.KSImageLoader;
import java.util.ArrayList;

/* loaded from: classes4.dex */
public final class c {
    public static final com.kwad.sdk.core.config.item.d aDd = new com.kwad.sdk.core.config.item.d("tkRenderTypeSwitch", false);
    public static final p aDe = new p("feedTKIdleTime", 0L);
    public static l aDf = new l("batchReportCatchLimit", 20);
    public static l aDg = new l("exceptionCollectorSwitch", 1);
    public static l aDh = new l("catchExceptionReportSwitch", 1);
    public static l aDi = new l("mediaPlayerLogReport", 0);
    public static l aDj = new l("didCopySwitch", 1);
    public static l aDk = new l("enableHodor", 0);
    public static l aDl = new l("speedLimitSwitch", 1);
    public static l aDm = new l("speedLimitThreshold", 200);
    public static l aDn = new l("ksNativeAdCustomSwitch", 0);
    public static l aDo = new l("compoAndSoThreadPoolCoreSize", 0);
    public static l aDp = new l("forceActivateAfterInstalled", 0);
    public static l aDq = new l("spliceVideoInteractionType", 0);
    public static l aDr = new l("feedLoadOptimizeType", 0);
    public static l aDs = new l("feedLoadOptimizeExternalEnable", 0);
    public static l aDt = new l("nativeAdSlideClickDisable", 0);
    public static s aDu = new s("uaid", "");
    public static p aDv = new p("uaidExpireSec", 0L);
    public static p aDw = new p("uaidRequestDelayTime", 5L);
    public static l aDx = new l("interstitialAdLoadProcessChange", 0);
    public static l aDy = new l("interstitialAdActivityOpt", 0);
    public static l aDz = new l("formAdExitInterceptSwitch", 0);
    public static l aDA = new l("adLeaveConfirmSwitch", 0);
    public static l aDB = new l("viewLandingPageTaskDuration", 15);
    public static l aDC = new l("rewardAdVideoPreCacheSize", 800);
    public static com.kwad.sdk.core.config.item.d aDD = new com.kwad.sdk.core.config.item.d("dataFlowAutoStartSwitch", false);
    public static p aDE = new p("deviceInfoDisableConfig", 0L);
    public static com.kwad.sdk.core.config.item.d aDF = new com.kwad.sdk.core.config.item.d("playerEnable", false);
    public static com.kwad.sdk.core.config.item.d aDG = new com.kwad.sdk.core.config.item.d("dynamicEnable", false);
    public static com.kwad.sdk.core.config.item.d aDH = new com.kwad.sdk.core.config.item.d("commercialLoggerDeviceSwitch", false);
    public static l aDI = new l("commercialLoggerSwitch", 1);
    public static s aDJ = new s("tkSoUrlV7a", "");
    public static s aDK = new s("tkSoUrlV8a", "");
    public static com.kwad.sdk.core.config.item.d aDL = new com.kwad.sdk.core.config.item.d("useTKSoAll", false);
    public static n aDM = new n("playerConfig", null);
    public static t aDN = new t("pkgNameList", new ArrayList(0));
    public static t aDO = new t("hostList", new ArrayList(0));
    public static t aDP = new t("crashGatherRateConfigList", new ArrayList(0));
    public static TipsConfigItem aDQ = new TipsConfigItem();
    public static com.kwad.sdk.core.config.item.c aDR = new com.kwad.sdk.core.config.item.c();
    public static InstallActivateReminderConfigItem aDS = new InstallActivateReminderConfigItem();
    public static f aDT = new f();
    public static com.kwad.sdk.core.config.item.e aDU = new com.kwad.sdk.core.config.item.e();
    public static m<Integer> aDV = new m<>("adTKGrayConfig");
    public static q aDW = new q("realtimeReportActions", "");
    public static r aDX = new r();
    public static l aDY = new l("appInstallNoticeSecond", 0);
    public static l aDZ = new l("installFloatingLayerPostion", 0);
    public static l aEa = new l("remindInstallStyle", 0);
    public static l aEb = new l("remindInstallTime", 60);
    public static l aEc = new l("watermarkKwaiIdSwitch", 0);
    public static l aEd = new l("insertScreenV2Switch", 0);
    public static l aEe = new l("insertScreenAutoPlaySwitch", 0);
    public static k aEf = new k("insertScreenV2ShowConfig");
    public static l aEg = new l("environmentDetectEnable", 0);
    public static l aEh = new l("simCardInfoEnable", 0);
    public static l aEi = new l("baseStationEnable", 0);
    public static l aEj = new l("sensorEventEnable2", 0);
    public static l aEk = new l("lpAutoDownloadApkSwitch", 1);
    public static l aEl = new l("autoDownloadUrlSwitch", 0);
    public static l aEm = new l("insertScreenAdType", 0);
    public static l aEn = new l("interstitialAutoCallAppCountDaily", 1);
    public static l aEo = new l("mediaControlPlaySwitch", 1);
    public static s aEp = new s("appStatusSoUrlV7a", "");
    public static s aEq = new s("appStatusSoUrlV8a", "");
    public static s aEr = new s("appStatusSoVersion", "");
    public static l aEs = new l("deeplinkCheckSwitch", -3);
    public static com.kwad.sdk.core.config.item.d aEt = new com.kwad.sdk.core.config.item.d("deeplinkWindowSwitch", false);
    public static i aEu = new i();
    public static com.kwad.sdk.core.config.item.d aEv = new com.kwad.sdk.core.config.item.d("adLiveSwitch", false);
    public static com.kwad.sdk.core.config.item.d aEw = new com.kwad.sdk.core.config.item.d("TKSwitch", true);
    public static s aEx = new s("TKSwitchExtra", "");
    public static com.kwad.sdk.core.config.item.d aEy = new com.kwad.sdk.core.config.item.d("llsidDisplaySwitch", true);
    public static com.kwad.sdk.core.config.item.d aEz = new com.kwad.sdk.core.config.item.d("TKJsonSubThread", true);
    public static com.kwad.sdk.core.config.item.d aEA = new com.kwad.sdk.core.config.item.d("reduceDeviceSigSwitch", true);
    public static com.kwad.sdk.core.config.item.d aEB = new com.kwad.sdk.core.config.item.d("personalRecommend", false);
    public static l aEC = new l("forceActivate", 0);
    public static l aED = new l("remindOpen", -1);
    public static com.kwad.sdk.core.config.item.d aEE = new com.kwad.sdk.core.config.item.d("viewVisibleCheckLegacy", false);
    public static s aEF = new s("nativeAndAnrDynamic", "");
    public static l aEG = new l("kwaiAppVersionSwitch", 1);
    public static com.kwad.sdk.core.config.item.d aEH = new com.kwad.sdk.core.config.item.d("disableLogcatOAID", false);
    public static s aEI = new s("userAgent");
    public static l aEJ = new l("biddingLogSwitch", 0);
    public static l aEK = new l("forceActiveThreshold", 5);
    public static l aEL = new l("forceActiveInterval", 3);
    public static l aEM = new l("hybridEnable", 1);
    public static com.kwad.sdk.core.config.item.d aEN = new com.kwad.sdk.core.config.item.d("wifiResumeDownload", false);
    public static h aEO = new h("adExposureAreaPercent", 0.3f);
    public static h aEP = new h("adExposureTime", -1.0f);
    public static h aEQ = new h("drawAdExposureAreaPercent", 0.7f);
    public static h aER = new h("apmToRECommercialRatio", 0.0f);
    public static com.kwad.sdk.core.config.item.d aES = new com.kwad.sdk.core.config.item.d("appInAdExposureBlacklist", false);
    public static com.kwad.sdk.core.config.item.d aET = new com.kwad.sdk.core.config.item.d("soDownloadBreakpointContinuation", true);
    public static l aEU = new l("soLoadMaxRetryCount", 1);
    public static com.kwad.sdk.core.config.item.d aEV = new com.kwad.sdk.core.config.item.d("feedAdForceGetAudioFocus", false);
    public static com.kwad.sdk.core.config.item.d aEW = new com.kwad.sdk.core.config.item.d("forceGetAudioFocus", false);
    public static l aEX = new l("feedAdWebviewOptimize", 1);
    public static com.kwad.sdk.core.config.item.d aEY = new com.kwad.sdk.core.config.item.d("logCommandSwitch", false);
    public static com.kwad.sdk.core.config.item.d aEZ = new com.kwad.sdk.core.config.item.d("logRecordAllSwitch", false);
    public static p aFa = new p("obiwanLogFilesDiskQuota", 52428800L);
    public static n aFb = new n("logCommandResult", "", false);
    public static p aFc = new p("validClickConvertTime", 1000L);
    public static com.kwad.sdk.core.config.item.d aFd = new com.kwad.sdk.core.config.item.d("eplCommandSwitch", false);
    public static l aFe = new l("playableAutoPlayEnable", 1);
    public static l aFf = new l("netMonitorSwitch", 0);
    public static com.kwad.sdk.core.config.item.d aFg = new com.kwad.sdk.core.config.item.d("ipDirectEnable", false);
    public static com.kwad.sdk.core.config.item.d aFh = new com.kwad.sdk.core.config.item.d("ipPreferEnable", false);
    public static l aFi = new l("weaponSwitch", 1);
    public static l aFj = new l("kvModeV2", 0);
    public static j aFk = new j();
    public static l aFl = new l("idcRollbackInterval", 0);
    public static p aFm = new p("currentServerTimeMs");
    public static l aFn = new l("clientProofreadTimeErrorRangeHours", 100);
    public static h aFo = new h("adTraceReportRate", 1.0f);
    public static l aFp = new l("adTraceRepeatEnable", 0);
    public static l aFq = new l("appHeartBeatInterval", 0);
    public static l aFr = new l("insertShowPercent", 100);
    public static l aFs = new l("adCacheCode", 0);
    public static s aFt = new s("installTipsContentDesc", "");
    public static s aFu = new s("installTipsPositiveActionDesc", "");
    public static s aFv = new s("installTipsNegativeActionDesc", "");
    public static com.kwad.sdk.core.config.item.d aFw = new com.kwad.sdk.core.config.item.d("threadOptEnable", false);
    public static com.kwad.sdk.core.config.item.d aFx = new com.kwad.sdk.core.config.item.d("resourceWarmupSwitch", false);
    public static l aFy = new l("resourceWarmupDelayTime", 5);
    public static s aFz = new s("perfMonitorV2", "");
    public static l aFA = new l("neoVideoAdaptStrategy", 1);
    public static l aFB = new l("feedTKLoadTimeOut", 2500);
    public static l aFC = new l("drawTKLoadTimeOut", Integer.valueOf(ZeusPluginEventCallback.EVENT_START_LOAD));
    public static com.kwad.sdk.core.config.item.d aFD = new com.kwad.sdk.core.config.item.d("adCacheOptEnable", false);
    public static l aFE = new l("adImageLoaderCacheLimitSize", -1);
    public static com.kwad.sdk.core.config.item.d aFF = new com.kwad.sdk.core.config.item.d("autoShowActivityMiddlePage", false);
    public static l aFG = new l("videoCacheOpt", 0);
    public static s aFH = new s("ranger", "");
    public static l aFI = new l("hdrConfig", 0);
    public static s aFJ = new s("packageInstall", "");
    public static s aFK = new s("eplV1", "");
    public static s aFL = new s("threadPoolPerfMonitor", "");
    public static s aFM = new s("threadPoolParams", "");
    public static g aFN = new g("crashUploadRate", Double.valueOf(1.0d));
    public static g aFO = new g("adFeedWidthMinPercent", Double.valueOf(0.3d));
    public static com.kwad.sdk.core.config.item.d aFP = new com.kwad.sdk.core.config.item.d("videoPerfMonitor", false);
    public static com.kwad.sdk.core.config.item.d aFQ = new com.kwad.sdk.core.config.item.d("enableHookPluginResource", true);
    public static com.kwad.sdk.core.config.item.d aFR = new com.kwad.sdk.core.config.item.d("enableHookWrapperContext", true);
    public static com.kwad.sdk.core.config.item.d aFS = new com.kwad.sdk.core.config.item.d("batchReportSkipJSONParseEnable", false);
    public static com.kwad.sdk.core.config.item.d aFT = new com.kwad.sdk.core.config.item.d("enableAdTrackLog", true);
    public static com.kwad.sdk.core.config.item.d aFU = new com.kwad.sdk.core.config.item.d("usePolicy64LevelDisable", false);
    public static com.kwad.sdk.core.config.item.d aFV = new com.kwad.sdk.core.config.item.d("tkReportInfoSwitch", false);
    public static l aFW = new l("tubeRenderType", 0);
    public static l aFX = new l("useTKAdBrowse", 0);
    public static com.kwad.sdk.core.config.item.d aFY = new com.kwad.sdk.core.config.item.d("enableMediaGetAdInfo", false);
    public static com.kwad.sdk.core.config.item.d aFZ = new com.kwad.sdk.core.config.item.d("ecExtInfoSwitch", false);
    public static s aGa = new s("trackBlackUrlConfig", "");
    public static l aGb = new l("tkMemCacheSize", 0);
    public static t aGc = new t("preloadMemCacheTemplateIds", new ArrayList(0));
    public static l aGd = new l("kGeoInfoConfig", 1);
    public static l aGe = new l("appMonitorSwitch", 0);
    public static l aGf = new l("videoCacheErrorCallbackSwitch", 0);
    public static l aGg = new l("tkErrorDetailCount", 1);
    public static l aGh = new l("videoLaunchOptimiseSwitch", 0);
    public static l aGi = new l("enableInitStartMode", 1);
    public static s aGj = new s("localLogConfig", "");
    public static s aGk = new s("adLogRetryConfig", "");
    public static o aGl = new o("dpSchemeFlags");
    public static com.kwad.sdk.core.config.item.d aGm = new com.kwad.sdk.core.config.item.d("feedAdBgTransparentSwitch");
    public static l aGn = new l("adRequestNum", 1);
    public static l aGo = new l("carouselInterval", Integer.valueOf(KSImageLoader.InnerImageLoadingListener.MAX_DURATION));
    public static p aGp = new p("packageInfoLimiter", 0L);
    public static com.kwad.sdk.core.config.item.d aGq = new com.kwad.sdk.core.config.item.d("showOptimizedProgress");
    public static l aGr = new l("optimizeProgressMethod", 0);
    public static l aGs = new l("splashLoadTimeOptimize", 0);
    public static p aGt = new p("splashVisibleCheckDelayTime", 500L);
    public static com.kwad.sdk.core.config.item.d aGu = new com.kwad.sdk.core.config.item.d("isWaynePlayerValid", false);
    public static com.kwad.sdk.core.config.item.d aGv = new com.kwad.sdk.core.config.item.d("isWaynePlayerAsDefaultPlayer", false);
    public static n aGw = new n("waynePlayerPlayConfig", null);
    public static l aGx = new l("waynePlayerSupportAndroidApi", 24);
    public static com.kwad.sdk.core.config.item.d aGy = new com.kwad.sdk.core.config.item.d("apkBroadcastReceiverSwitch", true);
    public static com.kwad.sdk.core.config.item.d aGz = new com.kwad.sdk.core.config.item.d("closureSwitch", false);
    public static com.kwad.sdk.core.config.item.d aGA = new com.kwad.sdk.core.config.item.d("closureVideoTwoSwitch", false);
    public static s aGB = new s("closureH5AuthUrl", "");
    public static s aGC = new s("closureH5AuthAppId", "");
    public static s aGD = new s("closureH5AuthPathPart", "");
    public static s aGE = new s("closureSupportSdkVersion", "4.8.30");
    public static com.kwad.sdk.core.config.item.d aGF = new com.kwad.sdk.core.config.item.d("enableThreadOpt2", false);
    public static n aGG = new n("cheatInfoConfig", null);
    public static n aGH = new n("featureCollectConfig", null);
    public static final l aGI = new l("installerCheckPkgAbSwitch", 0);
    public static final s aGJ = new s("installerCheckExtraPkgs", "");
    public static final l aGK = new l("probeBatch", 0);
    public static s aGL = new s("thKwaiMarketUrl", "");

    public static void init() {
    }
}
