package com.kwad.sdk.core.b.a;

import com.ksad.annotation.invoker.ForInvoker;
import com.kwad.sdk.commercial.j.a;
import com.kwad.sdk.commercial.model.HybridLoadMsg;
import com.kwad.sdk.commercial.model.SDKInitMsg;
import com.kwad.sdk.commercial.model.WebCloseStatus;
import com.kwad.sdk.commercial.model.WebViewCommercialMsg;
import com.kwad.sdk.commercial.model.WebViewLoadMsg;
import com.kwad.sdk.core.h.a;
import com.kwad.sdk.core.imageloader.ImageLoaderInfo;
import com.kwad.sdk.core.request.model.StatusInfo;
import com.kwad.sdk.core.response.model.ABParams;
import com.kwad.sdk.core.response.model.AdCouponReceiveParam;
import com.kwad.sdk.core.response.model.AdGlobalConfigInfo;
import com.kwad.sdk.core.response.model.AdInfo;
import com.kwad.sdk.core.response.model.AdMatrixInfo;
import com.kwad.sdk.core.response.model.AdProductInfo;
import com.kwad.sdk.core.response.model.AdStatusInfo;
import com.kwad.sdk.core.response.model.AdStyleInfo;
import com.kwad.sdk.core.response.model.AdTemplate;
import com.kwad.sdk.core.response.model.AdVideoPreCacheConfig;
import com.kwad.sdk.core.response.model.CouponInfo;
import com.kwad.sdk.core.response.model.FeedSlideConf;
import com.kwad.sdk.core.response.model.HttpDnsInfo;
import com.kwad.sdk.core.response.model.PageInfo;
import com.kwad.sdk.core.response.model.PhotoInfo;
import com.kwad.sdk.core.response.model.TKAdLiveShopItemInfo;
import com.kwad.sdk.core.response.model.TemplateConfig;
import com.kwad.sdk.core.response.model.VideoPlayerStatus;
import com.kwad.sdk.core.scene.URLPackage;
import com.kwad.sdk.internal.api.AdLabelImpl;
import com.kwad.sdk.internal.api.NativeAdExtraDataImpl;
import com.kwad.sdk.internal.api.SceneImpl;
import com.kwad.sdk.internal.api.SplashExtraDataImpl;
import com.kwad.sdk.o.l;
import java.util.HashMap;
import java.util.Map;

/* loaded from: classes4.dex */
public final class gu {
    public static Map<Class<? extends com.kwad.sdk.core.response.a.a>, com.kwad.sdk.core.d> aIC;

    static {
        HashMap map = new HashMap();
        aIC = map;
        map.put(AdMatrixInfo.RotateInfo.class, new jw());
        aIC.put(AdStyleInfo.PlayDetailInfo.class, new iu());
        aIC.put(AdInfo.AdMaterialInfo.MaterialFeature.class, new hi());
        aIC.put(com.kwad.sdk.commercial.i.a.class, new hg());
        aIC.put(com.kwad.sdk.commercial.a.b.class, new bj());
        aIC.put(AdMatrixInfo.AggregationCardInfo.class, new bd());
        aIC.put(AdMatrixInfo.ActivityMiddlePageInfo.class, new g());
        aIC.put(com.kwad.sdk.h.a.b.class, new il());
        aIC.put(TKAdLiveShopItemInfo.class, new lj());
        aIC.put(StatusInfo.NativeAdStyleControl.class, new hv());
        aIC.put(PhotoInfo.class, new it());
        aIC.put(PhotoInfo.BaseInfo.class, new bx());
        aIC.put(AdInfo.ComplianceInfo.class, new cq());
        aIC.put(AdMatrixInfo.SlideInfo.class, new ki());
        aIC.put(com.kwad.sdk.core.threads.b.class, new ls());
        aIC.put(AdInfo.CutRuleInfo.class, new dh());
        aIC.put(AdInfo.AdAggregateInfo.class, new h());
        aIC.put(VideoPlayerStatus.class, new ml());
        aIC.put(AdInfo.AdLiveTypeInfo.class, new af());
        aIC.put(SceneImpl.class, new kb());
        aIC.put(StatusInfo.SplashAdInfo.class, new kn());
        aIC.put(NativeAdExtraDataImpl.class, new hr());
        aIC.put(AdInfo.AdDrawInfo.class, new t());
        aIC.put(AdInfo.SmallAppJumpInfo.class, new kj());
        aIC.put(AdMatrixInfo.AdDataV2.class, new s());
        aIC.put(AdMatrixInfo.StyleInfo.class, new lh());
        aIC.put(com.kwad.sdk.core.request.model.f.class, new ln());
        aIC.put(AdMatrixInfo.ComponentTemplateInfo.class, new cs());
        aIC.put(AdInfo.AdConversionInfo.class, new m());
        aIC.put(AdMatrixInfo.RotateDegreeInfo.class, new jv());
        aIC.put(AdInfo.AdConversionInfo.DeeplinkItemInfo.class, new dl());
        aIC.put(com.kwad.sdk.commercial.f.b.class, new dm());
        aIC.put(AdStyleInfo.class, new au());
        aIC.put(AdMatrixInfo.FullScreenInfo.class, new ez());
        aIC.put(AdMatrixInfo.MatrixTag.class, new hl());
        aIC.put(AdMatrixInfo.NeoVideoInfo.class, new ic());
        aIC.put(SplashExtraDataImpl.class, new kp());
        aIC.put(AdInfo.RewardFraudVerifyInfo.class, new jl());
        aIC.put(AdMatrixInfo.SplashPlayCardTKInfo.class, new kt());
        aIC.put(AdInfo.UnDownloadConf.class, new lz());
        aIC.put(com.kwad.sdk.commercial.b.b.class, new bn());
        aIC.put(com.kwad.sdk.utils.b.a.class, new gz());
        aIC.put(AdGlobalConfigInfo.NeoScanAggregationSceneInfo.class, new ia());
        aIC.put(AdStyleInfo.PlayDetailInfo.DetailCommonInfo.class, new dn());
        aIC.put(ABParams.class, new a());
        aIC.put(AdMatrixInfo.ShakeInfo.class, new kc());
        aIC.put(AdMatrixInfo.InstalledActivateInfo.class, new gg());
        aIC.put(AdMatrixInfo.StyleComponentInfo.class, new lg());
        aIC.put(URLPackage.class, new lx());
        aIC.put(AdInfo.class, new y());
        aIC.put(AdMatrixInfo.AdInteractionInfo.class, new aa());
        aIC.put(AdStyleInfo.PlayDetailInfo.PatchAdInfo.class, new ir());
        aIC.put(AdInfo.AdFeedInfo.class, new u());
        aIC.put(AdStyleInfo.PlayEndInfo.EndTopToolBarInfo.class, new eb());
        aIC.put(AdInfo.AdShowVideoH5Info.class, new aq());
        aIC.put(AdGlobalConfigInfo.CycleAggregationInfo.class, new dj());
        aIC.put(com.kwad.sdk.commercial.c.a.class, new by());
        aIC.put(AdInfo.FullScreenVideoInfo.class, new fa());
        aIC.put(com.kwad.sdk.core.request.model.d.class, new id());
        aIC.put(AdStyleInfo.PlayEndInfo.class, new iw());
        aIC.put(AdInfo.UnDownloadRegionConf.class, new ma());
        aIC.put(com.kwad.sdk.commercial.e.b.class, new q());
        aIC.put(l.a.class, new mw());
        aIC.put(AdTemplate.class, new aw());
        aIC.put(SDKInitMsg.class, new jx());
        aIC.put(HttpDnsInfo.IpInfo.class, new go());
        aIC.put(AdMatrixInfo.SplashSlideInfo.class, new kx());
        aIC.put(a.C0413a.class, new ll());
        aIC.put(AdMatrixInfo.EndCardInfo.class, new ea());
        aIC.put(AdCouponReceiveParam.class, new p());
        aIC.put(AdInfo.AdMaterialInfo.class, new ak());
        aIC.put(AdStyleInfo.ExposeTagInfo.class, new ef());
        aIC.put(AdInfo.AdvertiserInfo.class, new bc());
        aIC.put(AdMatrixInfo.DynamicAdStyleInfo.class, new dz());
        aIC.put(AdInfo.DownloadSafeInfo.class, new dt());
        aIC.put(AdInfo.AdBaseInfo.class, new j());
        aIC.put(com.kwad.sdk.core.config.d.class, new im());
        aIC.put(AdMatrixInfo.Styles.class, new li());
        aIC.put(com.kwad.sdk.commercial.e.c.class, new r());
        aIC.put(WebViewCommercialMsg.class, new mt());
        aIC.put(AdProductInfo.class, new ao());
        aIC.put(AdInfo.H5Config.class, new fk());
        aIC.put(com.kwad.sdk.commercial.smallApp.b.class, new kk());
        aIC.put(AdStyleInfo.PlayDetailInfo.ActionBarInfo.class, new c());
        aIC.put(AdInfo.AdSplashInfo.class, new ar());
        aIC.put(AdMatrixInfo.MerchantLiveReservationInfo.LiveReservationPlayEndInfo.class, new hc());
        aIC.put(AdMatrixInfo.NativeMatrixAdInfo.class, new hx());
        aIC.put(com.kwad.sdk.commercial.g.b.class, new fn());
        aIC.put(com.kwad.sdk.core.network.j.class, new Cif());
        aIC.put(AdMatrixInfo.InterstitialCardInfo.class, new gk());
        aIC.put(AdStyleInfo.PlayDetailInfo.WidgetAdInfo.class, new mv());
        aIC.put(PhotoInfo.VideoInfo.class, new mg());
        aIC.put(AdMatrixInfo.RewardWebTaskCloseInfo.class, new jt());
        aIC.put(AdMatrixInfo.RewardVideoInteractInfo.class, new jr());
        aIC.put(AdInfo.RewardRetryTaskInfo.class, new jq());
        aIC.put(AdMatrixInfo.SplashEndCardTKInfo.class, new ko());
        aIC.put(l.a.C0434a.class, new la());
        aIC.put(AdMatrixInfo.RewardVideoTaskInfo.class, new js());
        aIC.put(AdMatrixInfo.CycleAggregateInfo.class, new di());
        aIC.put(TemplateConfig.class, new lp());
        aIC.put(AdStyleInfo.FeedAdInfo.class, new ej());
        aIC.put(AdMatrixInfo.TemplateData.class, new lr());
        aIC.put(AdInfo.AdStyleConfInfo.class, new at());
        aIC.put(AdMatrixInfo.FeedInfo.class, new el());
        aIC.put(com.kwad.sdk.core.threads.d.class, new lt());
        aIC.put(WebCloseStatus.class, new ms());
        aIC.put(AdMatrixInfo.BaseMatrixTemplate.class, new bz());
        aIC.put(StatusInfo.SplashStyleControl.class, new ky());
        aIC.put(AdGlobalConfigInfo.class, new w());
        aIC.put(AdInfo.NativeAdShakeInfo.class, new hu());
        aIC.put(FeedSlideConf.class, new eo());
        aIC.put(AdStyleInfo.PlayDetailInfo.DetailWebCardInfo.class, new dp());
        aIC.put(AdMatrixInfo.SplashInfo.class, new kq());
        aIC.put(HttpDnsInfo.class, new fs());
        aIC.put(AdStyleInfo.PlayDetailInfo.DrawAdInfo.class, new dw());
        aIC.put(AdInfo.AdTrackInfo.class, new ax());
        aIC.put(HybridLoadMsg.class, new ft());
        aIC.put(AdVideoPreCacheConfig.class, new ba());
        aIC.put(StatusInfo.class, new le());
        aIC.put(a.C0399a.class, new lw());
        aIC.put(AdMatrixInfo.class, new al());
        aIC.put(AdMatrixInfo.MerchantLiveReservationInfo.class, new hn());
        aIC.put(AdStatusInfo.class, new as());
        aIC.put(AdInfo.PlayableStyleInfo.class, new ja());
        aIC.put(AdStyleInfo.PlayDetailInfo.DetailTopToolBarInfo.class, new Cdo());
        aIC.put(AdStyleInfo.ExtraDisplayInfo.class, new eh());
        aIC.put(AdMatrixInfo.MatrixTemplate.class, new hm());
        aIC.put(AdStyleInfo.PlayEndInfo.AdWebCardInfo.class, new bb());
        aIC.put(AdInfo.MaterialSize.class, new hk());
        aIC.put(AdGlobalConfigInfo.RefreshToken.class, new jh());
        aIC.put(AdInfo.AdPreloadInfo.class, new an());
        aIC.put(com.kwad.sdk.core.request.model.b.class, new dq());
        aIC.put(com.kwad.sdk.commercial.j.b.class, new az());
        aIC.put(com.kwad.sdk.core.request.model.g.class, new me());
        aIC.put(ImageLoaderInfo.class, new fw());
        aIC.put(AdStyleInfo.AdBrowseInfo.class, new l());
        aIC.put(AdMatrixInfo.PreLandingPageTKInfo.class, new jc());
        aIC.put(AdMatrixInfo.BottomBannerInfo.class, new cd());
        aIC.put(AdMatrixInfo.DownloadTexts.class, new dv());
        aIC.put(AdMatrixInfo.SplashActionBarInfo.class, new km());
        aIC.put(CouponInfo.class, new de());
        aIC.put(AdInfo.NativeAdInfo.class, new hs());
        aIC.put(AdStyleInfo.PlayDetailInfo.PatchEcInfo.class, new is());
        aIC.put(AdInfo.CallBackStrategyInfo.class, new cf());
        aIC.put(StatusInfo.NativeAdRequestInfo.class, new ht());
        aIC.put(WebViewLoadMsg.class, new mu());
        aIC.put(AdInfo.AdInsertScreenInfo.class, new z());
        aIC.put(AdMatrixInfo.ComponentParam.class, new cr());
        aIC.put(AdProductInfo.SpikeInfo.class, new kl());
        aIC.put(AdInfo.AdBannerInfo.class, new i());
        aIC.put(com.kwad.sdk.h.a.a.class, new ik());
        aIC.put(com.kwad.sdk.core.network.i.class, new ie());
        aIC.put(AdMatrixInfo.InnerEcAuthInfo.class, new fy());
        aIC.put(com.kwad.sdk.core.report.j.class, new ec());
        aIC.put(AdInfo.AdRewardInfo.class, new ap());
        aIC.put(com.kwad.sdk.commercial.d.b.class, new n());
        aIC.put(AdLabelImpl.class, new ab());
        aIC.put(PageInfo.class, new io());
        aIC.put(AdMatrixInfo.ActionBarInfoNew.class, new d());
        Jc();
    }

    @ForInvoker(methodId = "registerHolder")
    private static void Jc() {
        ct.Jc();
        cu.Jc();
        cv.Jc();
        cw.Jc();
        cx.Jc();
        cy.Jc();
        cz.Jc();
        da.Jc();
        db.Jc();
        dc.Jc();
        es.Jc();
        et.Jc();
        eu.Jc();
        ev.Jc();
        ew.Jc();
        ex.Jc();
    }

    public static Map<Class<? extends com.kwad.sdk.core.response.a.a>, com.kwad.sdk.core.d> Jd() {
        return aIC;
    }

    public static com.kwad.sdk.core.d getHolder(Class<? extends com.kwad.sdk.core.response.a.a> cls) {
        return aIC.get(cls);
    }
}
