package com.bytedance.sdk.openadsdk.res.layout.h;

import android.R;
import android.content.Context;
import android.graphics.Color;
import android.graphics.drawable.StateListDrawable;
import android.text.TextUtils;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import androidx.core.view.GravityCompat;
import com.bytedance.sdk.component.utils.wv;
import com.bytedance.sdk.openadsdk.core.nd.m;

/* loaded from: classes.dex */
public class cg implements com.bytedance.sdk.openadsdk.res.layout.h {
    @Override // com.bytedance.sdk.openadsdk.res.layout.h
    public View bj(Context context) {
        LinearLayout linearLayout = new LinearLayout(context);
        linearLayout.setId(2114387602);
        linearLayout.setLayoutParams(new LinearLayout.LayoutParams(-1, -2));
        linearLayout.setBackgroundColor(-1);
        linearLayout.setOrientation(1);
        RelativeLayout relativeLayout = new RelativeLayout(context);
        relativeLayout.setId(2114387601);
        relativeLayout.setLayoutParams(new RelativeLayout.LayoutParams(-1, m.cg(context, 44.0f)));
        ImageView imageView = new ImageView(context);
        imageView.setId(2114387705);
        RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams.addRule(15);
        layoutParams.setMargins(m.cg(context, 5.0f), m.cg(context, 5.0f), m.cg(context, 5.0f), m.cg(context, 5.0f));
        imageView.setLayoutParams(layoutParams);
        imageView.setClickable(true);
        imageView.setFocusable(true);
        imageView.setPadding(m.cg(context, 5.0f), m.cg(context, 5.0f), m.cg(context, 5.0f), m.cg(context, 5.0f));
        int color = Color.parseColor("#6E6E6E");
        com.bytedance.sdk.openadsdk.res.h hVar = new com.bytedance.sdk.openadsdk.res.h(48);
        hVar.h(color);
        float fCg = m.cg(context, 2.0f);
        hVar.h(fCg);
        int color2 = Color.parseColor("#B1B1B1");
        com.bytedance.sdk.openadsdk.res.h hVar2 = new com.bytedance.sdk.openadsdk.res.h(48);
        hVar2.h(color2);
        hVar2.h(fCg);
        StateListDrawable stateListDrawable = new StateListDrawable();
        stateListDrawable.addState(new int[]{R.attr.state_pressed}, hVar);
        stateListDrawable.addState(new int[0], hVar2);
        imageView.setImageDrawable(stateListDrawable);
        relativeLayout.addView(imageView);
        ImageView imageView2 = new ImageView(context);
        imageView2.setId(2114387704);
        RelativeLayout.LayoutParams layoutParams2 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams2.addRule(15);
        layoutParams2.addRule(17, 2114387705);
        imageView2.setLayoutParams(layoutParams2);
        imageView2.setClickable(true);
        imageView2.setFocusable(true);
        imageView2.setPadding(m.cg(context, 5.0f), m.cg(context, 5.0f), m.cg(context, 5.0f), m.cg(context, 5.0f));
        com.bytedance.sdk.openadsdk.res.cg cgVar = new com.bytedance.sdk.openadsdk.res.cg(48);
        cgVar.h(color);
        cgVar.h(fCg);
        com.bytedance.sdk.openadsdk.res.cg cgVar2 = new com.bytedance.sdk.openadsdk.res.cg(48);
        cgVar2.h(color2);
        cgVar2.h(fCg);
        StateListDrawable stateListDrawable2 = new StateListDrawable();
        stateListDrawable2.addState(new int[]{R.attr.state_pressed}, cgVar);
        stateListDrawable2.addState(new int[0], cgVar2);
        imageView2.setImageDrawable(stateListDrawable2);
        relativeLayout.addView(imageView2);
        TextView textView = new TextView(context);
        textView.setId(2114387952);
        RelativeLayout.LayoutParams layoutParams3 = new RelativeLayout.LayoutParams(m.cg(context, 200.0f), -2);
        layoutParams3.addRule(13);
        layoutParams3.addRule(15);
        layoutParams3.setMargins(m.cg(context, 25.0f), 0, m.cg(context, 25.0f), 0);
        textView.setLayoutParams(layoutParams3);
        TextUtils.TruncateAt truncateAt = TextUtils.TruncateAt.MARQUEE;
        textView.setEllipsize(truncateAt);
        textView.setGravity(17);
        textView.setPadding(m.cg(context, 25.0f), 0, m.cg(context, 25.0f), 0);
        textView.setSingleLine(true);
        relativeLayout.addView(textView);
        TextView textView2 = new TextView(context);
        textView2.setId(2114387627);
        RelativeLayout.LayoutParams layoutParams4 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams4.addRule(21);
        layoutParams4.addRule(11);
        layoutParams4.addRule(15);
        layoutParams4.setMargins(0, 0, m.cg(context, 15.0f), 0);
        textView2.setLayoutParams(layoutParams4);
        textView2.setEllipsize(truncateAt);
        textView2.setGravity(GravityCompat.END);
        textView2.setSingleLine(true);
        textView2.setText(wv.h(context, "tt_feedback"));
        textView2.setTextColor(Color.parseColor("#808080"));
        relativeLayout.addView(textView2);
        linearLayout.addView(relativeLayout);
        LinearLayout linearLayout2 = new LinearLayout(context);
        linearLayout2.setId(2114387676);
        LinearLayout.LayoutParams layoutParams5 = new LinearLayout.LayoutParams(-1, m.cg(context, 77.0f));
        linearLayout2.setLayoutParams(layoutParams5);
        linearLayout2.setBackgroundColor(Color.parseColor("#ffffff"));
        linearLayout2.setOrientation(1);
        linearLayout2.setVisibility(8);
        View imageView3 = new ImageView(context);
        imageView3.setId(2114387600);
        imageView3.setLayoutParams(new LinearLayout.LayoutParams(-1, m.cg(context, 1.0f)));
        imageView3.setBackgroundColor(Color.parseColor("#F2F2F2"));
        linearLayout2.addView(imageView3);
        TextView textView3 = new TextView(context);
        textView3.setId(2114387610);
        LinearLayout.LayoutParams layoutParams6 = new LinearLayout.LayoutParams(-1, m.cg(context, 15.0f));
        layoutParams6.setMargins(m.cg(context, 16.0f), m.cg(context, 8.0f), m.cg(context, 16.0f), 0);
        textView3.setLayoutParams(layoutParams6);
        TextUtils.TruncateAt truncateAt2 = TextUtils.TruncateAt.END;
        textView3.setEllipsize(truncateAt2);
        textView3.setSingleLine(true);
        textView3.setTextColor(Color.parseColor("#999999"));
        textView3.setTextSize(2, 10.0f);
        linearLayout2.addView(textView3);
        TextView textView4 = new TextView(context);
        textView4.setId(2114387701);
        LinearLayout.LayoutParams layoutParams7 = new LinearLayout.LayoutParams(-1, m.cg(context, 15.0f));
        layoutParams7.setMargins(m.cg(context, 16.0f), m.cg(context, 7.0f), m.cg(context, 16.0f), 0);
        textView4.setLayoutParams(layoutParams7);
        textView4.setEllipsize(truncateAt2);
        textView4.setSingleLine(true);
        textView4.setTextColor(Color.parseColor("#999999"));
        textView4.setTextSize(2, 10.0f);
        linearLayout2.addView(textView4);
        RelativeLayout relativeLayout2 = new RelativeLayout(context);
        relativeLayout2.setId(2114387599);
        ViewGroup.LayoutParams layoutParams8 = new LinearLayout.LayoutParams(-1, -1);
        layoutParams5.setMargins(0, m.cg(context, 8.0f), 0, 0);
        relativeLayout2.setLayoutParams(layoutParams8);
        relativeLayout2.setBackgroundColor(Color.parseColor("#26C4C4C4"));
        TextView textView5 = new TextView(context);
        textView5.setId(2114387598);
        RelativeLayout.LayoutParams layoutParams9 = new RelativeLayout.LayoutParams(m.cg(context, 70.0f), -1);
        layoutParams9.addRule(20);
        layoutParams9.addRule(9);
        layoutParams9.addRule(10);
        layoutParams9.addRule(12);
        layoutParams9.setMargins(m.cg(context, 64.0f), 0, 0, 0);
        textView5.setLayoutParams(layoutParams9);
        textView5.setGravity(17);
        textView5.setText("应用权限");
        textView5.setTextColor(Color.parseColor("#1A73E8"));
        textView5.setTextSize(2, 12.0f);
        relativeLayout2.addView(textView5);
        View imageView4 = new ImageView(context);
        imageView4.setId(2114387597);
        RelativeLayout.LayoutParams layoutParams10 = new RelativeLayout.LayoutParams(m.cg(context, 0.5f), m.cg(context, 9.0f));
        layoutParams10.addRule(13);
        imageView4.setLayoutParams(layoutParams10);
        imageView4.setBackgroundColor(Color.parseColor("#D8D8D8"));
        relativeLayout2.addView(imageView4);
        TextView textView6 = new TextView(context);
        textView6.setId(2114387700);
        RelativeLayout.LayoutParams layoutParams11 = new RelativeLayout.LayoutParams(m.cg(context, 70.0f), -1);
        layoutParams11.addRule(21);
        layoutParams11.addRule(11);
        layoutParams11.addRule(10);
        layoutParams11.addRule(12);
        layoutParams11.setMargins(0, 0, m.cg(context, 64.0f), 0);
        textView6.setLayoutParams(layoutParams11);
        textView6.setGravity(17);
        textView6.setText("隐私协议");
        textView6.setTextColor(Color.parseColor("#1A73E8"));
        textView6.setTextSize(2, 12.0f);
        relativeLayout2.addView(textView6);
        linearLayout2.addView(relativeLayout2);
        linearLayout.addView(linearLayout2);
        return linearLayout;
    }
}
